version: '3.5'

services:
  ###
  # api
  ###

  api:
    build:
      context: .
      dockerfile: ./images/api/Dockerfile.development
    command: >
      sh -c "yarn nest:dev"
    container_name: plutus_api
    depends_on:
      - database
    env_file:
      - ./.config/.env
    image: plutus/api
    networks:
      - plutus_network
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    volumes:
      - ./src:/usr/app/src:cached

  ###
  # databases
  ###

  database:
    build:
      context: .
      dockerfile: ./images/database/Dockerfile.development
    container_name: plutus_database
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_NAME:-plutus}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-admin}
    image: plutus/database
    networks:
      - plutus_network
    ports:
      - "${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}"

networks:
  plutus_network:
    name: plutus_network
