####
# This stage installs the dependencies
####
FROM node:20.9.0 AS installer

WORKDIR /usr/app

COPY package.json /usr/app
COPY yarn.lock /usr/app

RUN yarn install

####
# This stage runs the build
####
FROM node:20.9.0-alpine AS composer

# install curl for healthchecks
RUN apk --no-cache add curl

WORKDIR /usr/app

COPY . /usr/app
COPY --from=installer /usr/app/node_modules /usr/app/node_modules
